# Set permalink for drafts and posts
# Note:  Not set sitewide, since it would cause pages to become subdirs
# See https://github.com/jekyll/jekyll/pull/3538
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      permalink: /bits/:year/:month/:day/:title/
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /bits/:year/:month/:day/:title/
excerpt_separator: <!--more-->
exclude:
  - Gemfile
  - Gemfile.lock
  - Procfile
  - gems
  - vendor
future: false
# Should switch to rouge so I can use clodeblocks
# See https://github.com/jekyll/jekyll/issues/3371
highlighter: pygments
markdown: kramdown
kramdown:
  # Behave more similarly to CommonMark HTML blocks, which allow markup
  parse_block_html: true
permalink: none
timezone: America/Denver
url:  https://kevinlocke.name

# vi: set sts=2 sw=2 et :
