excerpt_separator: <!--more-->
future: false
highlighter: pygments
markdown: kramdown
permalink: /bits/:year/:month/:day/:title/
timezone: America/Denver
url:  https://kevinlocke.name

# vi: set sts=2 sw=2 et :
