# Set permalink for drafts and posts
# Note:  Not set sitewide, since it would cause pages to become subdirs
# See https://github.com/jekyll/jekyll/pull/3538
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      permalink: /bits/:year/:month/:day/:title/
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /bits/:year/:month/:day/:title/
excerpt_separator: <!--more-->
exclude:
  - Gemfile
  - Gemfile.lock
  - Procfile
  - gems
  - vendor
future: false
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  # Behave more similarly to CommonMark HTML blocks, which allow markup
  parse_block_html: true

  # https://kramdown.gettalong.org/syntax_highlighter/rouge.html
  syntax_highlighter_opts:
    # Only use "real" text for ID generation
    auto_id_stripping: true
    # Set default language to plaintext to disable language guessing.
    # This is useful for non-fenced blocks I don't want to highlight.
    default_lang: plaintext
    # Disable syntax highlighting of inline code, which is distracting and
    # problematic since language is not usually detectable.
    # https://github.com/gettalong/kramdown/issues/286
    span:
      disable: true
permalink: none
# Note: Gems are listed here and in Gemfile for compatibility with Github Pages
# See https://help.github.com/articles/configuring-jekyll-plugins/
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
timezone: America/Denver
url:  https://kevinlocke.name

# vi: set sts=2 sw=2 et :
